Repository go-vikunja/vikunja, pull requests merged in 2025-08, with the labels that each got.

#1084 fix(user): persist status on email updates
  pkg/user/test.go
  pkg/user/update_email.go
  pkg/user/update_email_test.go
  pkg/user/user.go
  pkg/user/user_create.go
  pkg/user/user_email_confirm.go
Labels: next-release

#1001 feat: rebuild the gantt chart
  frontend/cypress/e2e/project/project-view-gantt.spec.ts
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/gantt/GanttChart.vue
  frontend/src/components/gantt/GanttChartBody.vue
  frontend/src/components/gantt/GanttRow.vue
  frontend/src/components/gantt/GanttRowBars.vue
  frontend/src/components/gantt/GanttTimelineHeader.vue
  frontend/src/components/gantt/GanttVerticalGridLines.vue
  frontend/src/components/gantt/primitives/GanttBarPrimitive.vue
  frontend/src/components/gantt/primitives/GanttChartPrimitive.vue
  frontend/src/components/gantt/primitives/GanttRowPrimitive.vue
  frontend/src/components/misc/keyboard-shortcuts/shortcuts.ts
  frontend/src/components/project/views/ProjectGantt.vue
  frontend/src/components/tasks/GanttChart.vue
  frontend/src/composables/useGanttBar.ts
  frontend/src/helpers/color/getTextColor.ts
  frontend/src/i18n/lang/en.json
  frontend/src/models/label.ts
Labels: codex, next-release

#1289 fix: normalize frontend version string
  Dockerfile
Labels: codex

#1300 fix: strip label syntax with parentheses from task title
  frontend/src/modules/parseTaskText.test.ts
  frontend/src/modules/parseTaskText.ts
Labels: codex
